name: FreeBSD Container

on:
  - workflow_call
  - workflow_dispatch

permissions:
  packages: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release tag
        run: echo "TAG=$(gh release view --json=tagName --jq=.tagName)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build container images
        uses: vmactions/freebsd-vm@v1
        with:
          envs: TAG
          usesh: true
          sync: sshfs
          copyback: false

          prepare: |
            sysctl net.inet.ip.forwarding=1

            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+https://pkg.freebsd.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y podman-suite qemu-user-static
            service qemu_user_static onestart

            sed -i '' -e 's/zfs/vfs/g' /usr/local/etc/containers/storage.conf
            mkdir -p /var/db/containers/storage
            podman login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io

          run: |
            echo "Tag: $TAG"

            if [ -z "$TAG" ]; then
              echo "No tag" >&2
              exit 1
            fi

            for i in amd64 arm64; do
              mkdir -p bin/$i
              fetch -o- https://github.com/cynix/freebsd-sing-box/releases/download/$TAG/sing-box-${TAG#v}-freebsd-$i.tar.gz | tar -C bin/$i/ -zxf- --no-same-owner sing-box
            done

            podman build --manifest=ghcr.io/cynix/sing-box:$TAG --network=host --platform=freebsd/amd64,freebsd/arm64 --pull=always .
            podman manifest push ghcr.io/cynix/sing-box:$TAG
            podman manifest push ghcr.io/cynix/sing-box:$TAG ghcr.io/cynix/sing-box:latest
